# -*- coding: utf-8 -*-
"""Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1avKLZyyPqOMq8X0JNkScgPMRtp11pp3J
"""

!git clone https://github.com/zihaohe123/speak-turn-emb-dialog-act-clf.git



# Commented out IPython magic to ensure Python compatibility.
# %cd speak-turn-emb-dialog-act-clf



!unzip data.zip -d data/

!pip install torch transformers



!unzip -l data.zip

!rm -r data

!unzip data.zip -d .

!ls data/mrda/

!pip uninstall -y transformers

!pip install transformers==4.12.5

!pip uninstall -y transformers tokenizers

!pip install transformers==4.28.1

!pip install transformers==4.28.1



!python run_mrda.py

!python run_dyda.py

!python run_swda.py